<?php

namespace app\core;

use Fpdf\Fpdf;

class PDFService {

    public function generateDeckQR(string $deckDisplayId, string $deckTitle, string $callerUsername) {
        $host = Application::$app->request->host();
        
        $pdf = new FPDF();
        $pdf->SetTitle($deckTitle . ' QR-code');
        $pdf->AddPage();

        $pdf->SetFont('Arial', 'B', 16);
        $pdf->SetY(10);
        $pdf->Cell(0, 10, "QR-code for MTGAR deck: {$deckTitle}", 0, 2, 'C');

        $pdf->SetFont('', '', 12);
        $pdf->Cell(0, 10, "Generated by {$callerUsername} on " . date('d-m-Y @ H:i'), 0, 2, 'C');

        $pdf->Image("http://chart.googleapis.com/chart?cht=qr&chs=256x256&chl=http://{$host}/decks/view?d={$deckDisplayId}", 60, 30, 90, 0, 'PNG');

        $pdf->Output('I', "{$deckDisplayId}_QR.pdf");
    }

}